export const FETCH_STORIES_REQUEST = 'FETCH_STORIES_REQUEST'
export const FETCH_STORIES_SUCCESS = 'FETCH_STORIES_SUCCESS'
export const FETCH_STORIES_FAIL = 'FETCH_STORIES_FAIL'

export const FETCH_STORY_REQUEST = 'FETCH_STORY_REQUEST'
export const FETCH_STORY_SUCCESS = 'FETCH_STORY_SUCCESS'
export const FETCH_STORY_FAIL = 'FETCH_STORY_FAIL'